trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:
- script: |
    wget -c https://apache.newfountain.nl//jmeter/binaries/apache-jmeter-5.4.1.tgz
    tar -xf apache-jmeter-5.4.1.tgz
  displayName: 'Install the dependency packages'
  
- script: |
        apache-jmeter-5.4.1/bin/./jmeter -Jjmeter.reportgenerator.overall_granularity=1000 -n -t test.jmx -l results/log.jtl -j results/output.log -e -o report
  displayName: 'Run JMeter'

- script: |
    JMETER_RESULTS=results/log.jtl
    JUNIT_RESULTS=output.xml
    python3 jtl_junit_converter.py $JMETER_RESULTS $JUNIT_RESULTS
  displayName: 'RESULTS: Convert JMeter Results to JUnit Format'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'output.xml'
    failTaskOnFailedTests: true
  displayName: 'RESULTS: Publish Load Testing Results'

- publish: $(System.DefaultWorkingDirectory)/results
  artifact: jmeter-results
  condition: succeededOrFailed()
  displayName: 'RESULTS: Publish Load Test Artifacts'
  
- task: PublishPipelineArtifact@1
  displayName: 'Publish JMeter HTML Report'
  inputs:
    targetPath: report
    artifact: jmeter-report
